### ISSUE TITLE
Comments and whitespace in a complicated selector are not seen by stringifier

### ISSUE THREAD

**Issue by dfreedm** [PolymerLabs/shady-css-parser#10]
Given a sheet

``` css
.foo,
.bar,
/* comment */
.baz {
  border: 2px solid black;
}
```

and a stringifier

``` js
class Stringifer extends shadyCssParser.Stringifier {
  comment() {
    return '';
  }
}
```

Output is expected to be

``` css
.foo,.bar,.baz{border:2px solid black;}
```

but is instead

``` css
.foo,
.bar,
/* comment */
.baz {border:2px solid black;}
```
