### ISSUE TITLE
Multiple semi-colons after a property truncate the rest of the rule

### ISSUE THREAD

**Issue by dfreedm** [PolymerLabs/shady-css-parser#5]
Example:

``` css
x-foo {
  --foo: orange;;
  display: block;
  background: var(--foo);
}
```

Expected:

``` css
x-foo{--foo:orange;display:block;background:var(--foo);}
```

Actual:

``` css
x-foo{--foo:orange;}
```
